### ISSUE TITLE
SharePoint_SP-hosted_Add-Ins_Tutorials/9_BeforeHostWebData/ Error

### ISSUE THREAD

**Issue by mandolinrick** [OfficeDev/SharePoint_SP-hosted_Add-Ins_Tutorials#2]
When I run these scripts, I get the following errors:
1. File '/_layouts/15/sp.runtime.js' was not found.	EmployeeOrientation	C:\Users\RTorzynski\Documents\Visual Studio 2015\Projects\EmployeeOrientation\EmployeeOrientation\EmployeeOrientation\Pages\Default.aspx

2. File '/_layouts/15/sp.js' was not found.	EmployeeOrientation	C:\Users\RTorzynski\Documents\Visual Studio 2015\Projects\EmployeeOrientation\EmployeeOrientation\EmployeeOrientation\Pages\Default.aspx

3. Element 'ScriptLink' is not a known element. This can occur if there is a compilation error in the Web site, or the web.config file is missing.	EmployeeOrientation	C:\Users\RTorzynski\Documents\Visual Studio 2015\Projects\EmployeeOrientation\EmployeeOrientation\EmployeeOrientation\Pages\Help.aspx

the clientContext variable relies on this library.  I am using F5 to deploy to my development site.

Is there a correct location for  sp.runtime.js and sp.js for development sites?

Regards,

Rick Torzynski
Richard.Torzynski@aprenergy.com

**Comment by Rick-Kirkham** [comment]
I cannot reproduce these errors. 

`/_layouts/15` is a virtual folder shared by all websites on the SP farm (or SP Online tenancy). The files sp.runtime.js and sp.js are always there. 

`ScriptLink` is a class defined in the Microsoft.SharePoint assembly which should be in the GAC of every SharePoint server (including the host servers of SP online). 

If you are working with an on-premise SP server, I suggest you reboot the SP server. If the errors persist, that would suggest that something went wrong with the installation of SharePoint. If you manually navigate to the physical \layouts folder (%ProgramFiles%\Common Files\Microsoft Shared\web server extensions\15\TEMPLATE\LAYOUTS) can you find the 2 *.js files there? 

Another possibility is that your errors are a misleading side effect of some other problem. Be sure that you create your developer site with the Developer Site template. See [Create a developer site on an existing Office 365 subscription](https://msdn.microsoft.com/en-us/library/office/jj692554.aspx ) or [Set up an on-premises development environment for SharePoint Add-ins](https://msdn.microsoft.com/en-us/library/office/fp179923.aspx)

**Comment by mandolinrick** [comment]
Thank you for responding.  I just downloaded the code from github, and opened it up in Visual Studio 2015 (which did some conversion from previous version).  When I ran it (F5), it ran without errors.  So looks like issue was on my end.  I am using a using a developer site created with the Developer Site template.

Rick Torzynski
