### ISSUE TITLE
No search results displayed

### ISSUE THREAD

**Issue by BamideleAriwodola** [OfficeDev/SharePoint_SP-hosted_Add-Ins_Tutorials#4]
Hello,

When I press the F5 key, the program launches my browser and then I enter a search query like "sharepoint" and I get the exception as attached. I have a couple of documents on my development side and I'm entering a query based on those documents
![jserror](https://cloud.githubusercontent.com/assets/23080445/26365249/f0c39e96-3fde-11e7-82c1-46ec706306ad.png)

Please help.

**Comment by Rick-Kirkham** [comment]
@BamideleAriwodola 
Thanks for bringing this up. However, the Issues feature is intended for bugs in this particular sample. For technical help questions, please ask a question on StackOverflow. Be sure and tag it "sharepoint".
