### ISSUE TITLE
Cannot add as webpart

### ISSUE THREAD

**Issue by Zavael** [OfficeDev/SharePoint_SP-hosted_Add-Ins_Tutorials#5]
I downloaded the Before workflow sollution (that should be the code from the section "Add a WebPart to a page...") but after succesfull deploy, I cannot add this to my home page as a webPart nor as appPart, despite the section title that states this capability. I can open the app on my o365 Sharepoint as a full page, but it is not listen in the ribbon to select as a webpart when editing my page.

**Comment by Rick-Kirkham** [comment]
The tutorial doesn't try and teach every variation. In this case, the WebPart is designed to be embedded in the Default.aspx page as soon as it opens. If that is happening, then the solution is working as intended. For more advanced scenarios in which a WebPart can be added to multiple pages through the WebPart and Insert tabs of the ribbon, see [Create Add-in Parts ... ](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/create-add-in-parts-to-install-with-your-sharepoint-add-in)
